name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: fedora-latest
    steps:
    - uses: actions/checkout@v3

    - name: Compiling program
      run: cmake -G "Unix Makefiles"

    - name: Display
      run: ls
    
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Running cmake
      run: cmake -G "Visual Studio 17 2022"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Compiling Programm
      run: |
        ls _deps
        msbuild .\Orizon.sln
