name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Downloading openGL
      run: |
        sudo apt-get update
        sudo apt-get install gcc-10 g++-10
        sudo apt-get install libstdc++-10-dev
        sudo apt-get install libpthread-stubs0-dev
        sudo apt-get install libgl1-mesa-dev
        sudo apt-get install libx11-dev
        sudo apt-get install libxrandr-dev
        sudo apt-get install libxcursor-dev
        sudo apt-get install libxinerama-dev 
        sudo apt-get install libxi-dev
        sudo apt-get install libfreetype6-dev
        sudo apt-get install libsndfile1-dev
        sudo apt-get install libopenal-dev
        sudo apt-get install libudev-dev

    - name: Generating Makefile
      run: cmake -G "Unix Makefiles"

    - name: Compiling program
      run: make
    
    - name: Display
      run: ls
    
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Running cmake
      run: cmake -G "Visual Studio 17 2022"

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Compiling Programm
      run: |
        ls _deps
        msbuild .\Orizon.sln
